ppw_labku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from story_3 import urls as story_3_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(story_3_urls), name="index")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story_1/urls.py
from django.urls import path
from .views import index
#url for app
urlpatterns = [
    path('', index, name='index'),
]

story_3/urls.py
from django.urls import path
from . import views
# url for app
app_name = 'story_3'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('skill/', views.skill, name='skill'),
    path('experience/', views.experience, name='experience'),
    path('contact/', views.contact, name='contact'),
    path('register/', views.register, name='register'),
    path('schedule/add/', views.schedule_creation, name='schedule_creation'),
    path('schedule/', views.schedule_list, name='schedule_list'),
    path('delete/', views.schedule_drop_all, name='schedule_drop_all'),
]

story_1/models.py
from django.db import models

# Create your models here.

story_3/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    day = models.CharField(max_length=10, null=True)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

story_3/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'day', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

story_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Ray Azrin Karim'
curr_year = int(datetime.now().strftime("%Y"))
# TODO Implement this, format (Year, Month, Date)
birth_date = date(2000, 4, 19)
npm = 1706044111  # TODO Implement this
university = 'Universitas Indonesia'
hobby = 'reading books, watching movies, and listening to music'
# Create your views here.


def index(request):
    response = {'name': mhs_name, 'age': calculate_age(
        birth_date.year), 'npm': npm, 'univ': university, 'hobby': hobby}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

story_3/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms

# Create your views here.


def index(request):
    return render(request, 'base_home.html')


def about(request):
    return render(request, 'base_about.html')


def education(request):
    return render(request, 'base_education.html')


def skill(request):
    return render(request, 'base_skill.html')


def experience(request):
    return render(request, 'base_experience.html')


def contact(request):
    return render(request, 'base_contact.html')


def register(request):
    return render(request, 'base_register.html')


def schedule_list(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'base_schedule_list.html', {'schedules': schedules})


def schedule_creation(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story_3:schedule_list')

    else:
        form = forms.ScheduleForm()
    return render(request, 'base_schedule_creation.html', {'form': form})


def schedule_drop_all(request):
    Schedule.objects.all().delete()
    return redirect('story_3:schedule_list')

story_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
    <link rel="stylesheet" href="{% static " css/style.css" %}">
</head>

<body>
    <div id="saya">
        <a href="https://www.linkedin.com/in/ray-azrin-0365a8155/" target="_blank"><img src="{% static "image/ray.png" %}" alt="Ray Azrin Karim" style="width: 30vw;height: 30vw;"></a>
        <div class="text">
            <h1>Hello, my name is {{ name }}</h1>
            <p><strong>NPM : {{ npm }}
                <br>I am {{ age }} years old
                <br>Currently I'm majoring Information System Bachelor Degree at {{ univ }}
                <br>My hobby is {{ hobby }}</strong>
                <br>
                <br>It takes a while to get to know Ray Azrin Karim, but the biggest two things to know are that he's farsighted and insightful.
                <br>Of course he's also adaptable, innovative and sweet, but those are often overshadowed by tendencies of being blunt as well. <br><br><br><br><br>
            </p>
        </div>
    </div>

    <div id="depan">
        <img src="{% static "image/fotojihan.jpg" %}" alt="Ray Azrin Karim" style="width: 30vw;height: 30vw;">
        <div class="text">
            <h1>Her name is Jihan Maulana Octa</h1>
            <p><strong>NPM : 1706984644
                <br>She is 18 years old
                <br>Currently she's majoring Information System Bachelor Degree at {{ univ }}
                <br>Her hobby is Singing</strong>
                <br>
                <br>She's interested to work as a Product Manager <br><br><br><br><br>
            </p>
        </div>
    </div>

    <div id="belakang">
        <img src="{% static "image/fotoyosafat.jpg" %}" alt="Ray Azrin Karim" style="width: 30vw;height: 30vw;">
        <div class="text">
            <h1>His name is Yosafat Tri Putra Brata</h1>
            <p><strong>NPM : 1706043430
                <br>He is 19 years old
                <br>Currently he's majoring Information System Bachelor Degree at {{ univ }}
                <br>His hobby is playing games and sleeping</strong>
                <br>
                <br>He's from Jambi, small city from Sumatra. You can call him Yosafat
            </p>
        </div>
    </div>
</body>

</html>

story_3/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">

        <title>
            {% block title %}{% endblock %}
        </title>
    </head>

    <body>
        <div>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark-red">
                <a class="navbar-brand" href="#">PPW Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{% url 'story_3:index' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:about' %}">About</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:education' %}">Education</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:skill' %}">Skill</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:experience' %}">Experience</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:contact' %}">Contact</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:register' %}">Register</a>
                        <a class="nav-item nav-link" href="{% url 'story_3:schedule_list' %}">Schedule</a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <footer class="footer text-right">
            <div class="container">
                <span class="small text-muted">web design and programming course 2018
                </span>
            </div>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>

    </body>

</html>

story_3/templates/base_about.html
{% extends 'base.html' %}
{% load static %}

{% block title%}About me{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">ABOUT ME</h1>
    <p class="lead text-center">A brief story about my life</p>
    <div class="row">
        <div class="col-sm-6 text-center">
            <img src="{% static "img/about.jpg" %}" class="rounded-circle img-fluid" id="resize">
        </div>
        <div class="col-sm-6 text-justify">
            My interest in computing has not been restricted to the classroom and college life. Within the last twelve months I’ve used the knowledge that I’ve gained over the past twelve years together with the help of my family to set up my own computer
            related business. This has given me a totally new perspective on how certain things function, and how business operates. The writing of a business plan was a totally alien experience for me, but over the course of 9 months I researched and planned,
            and finally when the plan was complete I was rewarded with the satisfaction of knowing that I had completed something that most people would never have the chance to do especially at my age. Through the setting up of the company and its subsequent
            running I have learnt many things. These include how to balance tasks effectively, how critical teamwork can be and how to delegate tasks to get the job done quickly and efficiently.
            <br><br>
            I’m looking forward with great anticipation to the challenges that studying for a degree in computer science will bring.
        </div>
    </div>
{% endblock %}

story_3/templates/base_contact.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Contact me{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">CONTACT ME</h1>
    <p class="lead text-right">Looking forward to answer your email.
        <br>Feel free to send me an email here.</p>
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm-5">
            <p>Cell &emsp;&emsp;&emsp;+62 878-8317-7019
                <br>
                E-mail &emsp;&emsp;rayazrin19@gmail.com
                <br>
                Line &emsp;&emsp;&emsp;rayazrin19
                <br>
                Address &emsp;Jl. Juragan Sinda II No.15</p><br><br><br><br><br>
            <p>Social Media</p>
            <div class="d-inline-block">
                <a href="https://twitter.com/razrinn/"><img src="{% static "img/twitter.png"%}" id="resize-small"></a>
                <a href="https://facebook.com/rayazrk"><img src="{% static "img/fb.png"%}" id="resize-small"></a>
                <a href="https://instagram.com/razrinn"><img src="{% static "img/ig.png"%}" id="resize-small"></a>
                <a href="https://www.linkedin.com/in/ray-azrin-0365a8155/"><img src="{% static "img/linkedin.png"%}" id="resize-small"></a>

            </div>
        </div>

        <div class="col-sm"></div>
        <div class="col-sm-5">
            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Name*</label>
                    <input type="text" class="form-control" id="inputName" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address*</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Message*</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary float-right">Send</button>
            </form>
        </div>
    </div>
{% endblock %}

story_3/templates/base_education.html
{% extends 'base.html' %}
{% load static %}

{% block title%}My Education{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">MY EDUCATION</h1>
    <div class="text-center" id="education">
        <div class="d-inline-block">
            <img src="{% static "img/smp.png"%}" class="rounded float-left img-fluid" id="education-smp">
            <p class="text-center">
                SMPN 2 BEKASI
                <br>
                (2011-2014)
            </p>
        </div>
        <div class="d-inline-block">
            <img src="{% static "img/sma.png"%}" class="rounded mx-auto d-block img-fluid" id="education-sma">
            <p class="text-center">
                SMAN 1 BEKASI
                <br>
                (2014-2017)
            </p>
        </div>
        <div class="d-inline-block">
            <img src="{% static "img/kuliah.png"%}" class="rounded float-right img-fluid">
            <p class="text-center">
                UNIVERSITAS INDONESIA
                <br>
                (2017-NOW)
            </p>
        </div>
    </div>
    <div class="text-center">
        <img src="{% static "img/edu.png" %}" class="img-fluid" style="width: 10%">
    </div>
{% endblock %}

story_3/templates/base_experience.html
{% extends 'base.html' %}
{% load static %}

{% block title%}My Working Experience{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">MY WORKING EXPERIENCE</h1>
    <div class="row text-center">
        <div class="col-sm-4">
            <img src="{% static "img/bem.jpg" %}" class="rounded-circle img-fluid" id="resize">
            <p>Staff of Academic and Leadership Department BEM Fasilkom UI 2018</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static "img/fuki.png" %}" class="rounded-circle img-fluid" id="resize">
            <p>Staff of Muslim Development Center FUKI Fasilkom UI 2018</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static "img/compfest.jpg" %}" class="rounded-circle img-fluid" id="resize">
            <p>Staff of Business IT Case Competition Compfest X</p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-sm-2"></div>
        <div class="col-sm-4">
            <img src="{% static "img/okk.jpg" %}" class="rounded-circle img-fluid" id="resize">
            <p>Mentor OKK UI 2018
            </div>
            <div class="col-sm-4">
                <img src="{% static "img/pmb.jpg" %}" class="rounded-circle img-fluid" id="resize">
                <p>Staff of Supporting PMB Fasilkom UI 2018</p>
            </div>
            <div class="col-sm-2"></div>
        </div>

    {% endblock %}

story_3/templates/base_home.html
{% extends 'base.html' %}
{% load static %}

{% block title%}My Profile{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">I AM RAY AZRIN</h1>
    <p class="lead text-center">Software Engineer. Product Manager. Web Developer</p>
    <div class="row" id="home">
        <div class="col-sm-6 order-sm-1 order-2">
            <p class="font-grey">
                Full Name : Ray Azrin Karim
                <br>
                Birthday : April 19th, 2000
                <br>
                Interest : Computer and techonlogies stuff
                <br>
                Occupation : Student
                <br>
                Nationality : Indonesian
                <br>
                Hobbies : Listening to music and reading books
            </p><br><br><br><br>
            <p>
                <strong>Information System student that strives to be a better person than himself yesterday.</strong>
            </p>
        </div>
        <div class="col-sm-6 order-sm-2 order-1">
            <img src="{% static "img/ray.jpg"%}" alt="" class="img-fluid rounded-circle" id="resize">
        </div>
    </div>
{% endblock %}

story_3/templates/base_register.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Register Here{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">REGISTER</h1>
    <p class="lead text-center">Be a member</p>
    <form>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-5">
                <label for="exampleName">Name</label>
                <input type="email" class="form-control" id="exampleName" placeholder="Fullname">
            </div>
            <div class="form-group col-sm-5">
                <label for="exampleBirth">Birthdate</label>
                <input type="date" class="form-control" id="exampleName">
            </div>
            <div class="col-sm-1"></div>

        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <label for="exampleUsername">Username</label>
                <input type="text" class="form-control" id="exampleUsername" placeholder="Username">
            </div>
            <div class="col-sm-1"></div>
        </div>

        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-5">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group col-sm-5">
                <label for="exampleInputPassword1">Confirm Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                <br><br>
            </div>
            <div class="col-sm-1"></div>

        </div>

        <button type="submit" class="btn btn-primary float-right">Register</button>
    </form>
{% endblock %}

story_3/templates/base_schedule_creation.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Schedules{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">ADD SCHEDULE</h1>
    <form action="{% url 'story_3:schedule_creation' %}" method="post">
        {% csrf_token %}
        <div class="form-row">

            {% for field in form %}
                {% if field.label == 'Day'%}
                    <div class="col-sm-1"></div>
                    <div class="form-group col-sm-5">
                        {{ field.label_tag }}
                        <br>
                        {{ field }}
                    </div>
                {% elif  field.label == 'Date'%}
                    <div class="form-group col-sm-5">
                        {{ field.label_tag }}
                        <br>
                        {{ field }}
                    </div>
                    <div class="col-sm-1"></div>
                {% else %}
                    <div class="col-sm-1"></div>
                    <div class="form-group col-sm-10">
                        {{ field.label_tag }}
                        <br>
                        {{ field }}
                    </div>
                    <div class="col-sm-1"></div>

                {% endif %}
            {% endfor %}
            <div class="col-sm-10"></div>
            <input type="submit" class="btn btn-primary float-right" value="Add Schedule">
        </div>
    </form>
{% endblock %}

story_3/templates/base_schedule_list.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Schedules{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">SCHEDULE</h1>
    <div class="article">
        <a href="{% url 'story_3:schedule_drop_all' %}"><img src="{% static 'img/remove.png' %}" id="resize-small" class="float-right"></a>
        <a href="{% url 'story_3:schedule_creation' %}"><img src="{% static 'img/add.png' %}" id="resize-small" class="float-right"></a>
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <h2 class="jadwal">{{ schedule.activity }}</h2>
                        <p>{{ schedule.day }},
                            {{ schedule.date.date }}<br>
                            {{ schedule.time}}<br>
                            {{ schedule.place }}<br>
                            {{ schedule.category }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

story_3/templates/base_skill.html
{% extends 'base.html' %}
{% load static %}

{% block title%}My Technical Skill{% endblock %}

{% block content %}
    <h1 class="display-4 color-white text-center">MY TECHNICAL SKILL</h1>
    <p class="lead">My technical skills is mostly contains with something related to the computer programming</p>

    <div class="text-center">
        <img src="{% static "img/skill.png" %}" class="img-fluid" id="resize-small">
        <p>JAVA</p>
        <div class="progress">
            <div class="progress-bar bg-secondary" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
        </div><br>
        <p>PYTHON</p>
        <div class="progress">
            <div class="progress-bar bg-secondary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
        </div><br>
        <p>HTML</p>
        <div class="progress">
            <div class="progress-bar bg-secondary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
        </div><br>
        <p>CSS</p>
        <div class="progress">
            <div class="progress-bar bg-secondary" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
        </div><br>
        <p>JAVASCRIPT</p>
        <div class="progress">
            <div class="progress-bar bg-secondary" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
{% endblock %}